name: codestyle

on:
  merge_group:
  pull_request:

jobs:
  lint:
    name: lint:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: Check JS Codestyle
        run: pnpm codestyle:check
