name: release

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+b[0-9]+'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://www.npmjs.com/package/@dfinity/typedoc-plugin-icp-docs
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Python
        uses: dfinity/ci-tools/actions/setup-python@main

      - name: Setup Commitizen
        uses: dfinity/ci-tools/actions/setup-commitizen@main

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main

      - name: Build NPM package
        run: pnpm build

      # - name: Generate release notes
      #   uses: dfinity/ci-tools/actions/generate-release-notes@main

      - name: Publish to npm
        env:
          NPM_CONFIG_PROVENANCE: 'true'
        run: |
          pnpm publish --verbose --access public

      - name: Create Github release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          bodyFile: 'RELEASE_NOTES.md'
          tag: '${{ github.ref_name }}'
          commit: 'main'
          prerelease: false
          makeLatest: true
